### ISSUE TITLE
Make web generator

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/solidity-template#5]
# Inspiration

https://wizard.openzeppelin.com/#erc20

# Work plan

- [ ] Loads from any contract here (we need NPM releases first?)
- [ ] Can configure
- [ ] Can deploy with one button
- [ ] Can open remix
- [ ] Can download dapp template

**Comment by dtedesco1** [comment]
Can we just adapt the OpenZepplin Wizard app directly?

Here's the whole thing:  https://github.com/OpenZeppelin/contracts-wizard
